---
- name: Install dependencies
  apt:
    name: 
      - curl
      - apt-transport-https
      - ca-certificates
      - conntrack
    state: present
    update_cache: yes

- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker && systemctl start docker
  args:
    executable: /bin/bash

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Download and install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm -f kubectl
  args:
    executable: /bin/bash

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- debug:
    msg: "kubectl installed: {{ kubectl_version.stdout_lines }}"

- name: Download and install Minikube
  shell: |
    curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    rm -f minikube-linux-amd64
  args:
    executable: /bin/bash

- name: Verify Minikube installation
  command: minikube version
  register: minikube_version
  changed_when: false
    
- name: Start Minikube with Docker (force mode)
  shell: sudo minikube start --driver=docker --force

- debug:
    msg: "Minikube installed: {{ minikube_version.stdout_lines }}"

